name: fast_barcode_scanner_platform_interface
description: A common platform interface for the fast_barcode_scanner plugin.
homepage: https://github.com/jhoogstraat/fast_barcode_scanner/tree/master/fast_barcode_scanner_platform_interface
repository: https://github.com/jhoogstraat/fast_barcode_scanner
version: 2.0.0-dev.4

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
